/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

import * as React from 'react';
import * as renderer from 'react-test-renderer';

import Unsubscribe from '../unsubscribe';
import { IUnsubscribeData } from '../unsubscribe.data';
import { IUnsubscribeConfig, IUnsubscribeProps } from '../unsubscribe.props.autogenerated';

const mockData: IUnsubscribeData = {
    actionResponse: {
        text: 'Sample Response Data'
    }
};

const mockConfig: IUnsubscribeConfig = {
    showText: 'unsubscribe'
};

const mockActions = {};

describe('Unsubscribe', () => {
    let moduleProps: IUnsubscribeProps<IUnsubscribeData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IUnsubscribeProps<IUnsubscribeData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<Unsubscribe {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
