/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/* eslint-disable no-duplicate-imports */
import CheckoutGuestProfile from './checkout-guest-profile';
import CheckoutGuestProfileView from './checkout-guest-profile.view';

export * from './checkout-guest-profile';
export * from './checkout-guest-profile.data';
export {
    ICheckoutGuestProfileConfig,
    ICheckoutGuestProfileProps,
    ICheckoutGuestProfileResources
} from './checkout-guest-profile.props.autogenerated';
export * from './checkout-guest-profile.view';
export * from './components';

export { CheckoutGuestProfile, CheckoutGuestProfileView };
