/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';
import { ICodOrderConfirmationData } from './cod-order-confirmation.data';
import { ICodOrderConfirmationProps } from './cod-order-confirmation.props.autogenerated';

export interface ICodOrderConfirmationViewProps extends ICodOrderConfirmationProps<ICodOrderConfirmationData> {
    queryParams: URLSearchParams;
    orderId?: string;
    isCod: boolean;
    isLoading: boolean;
}

/**
 *
 * CodOrderConfirmation component
 * @extends {React.PureComponent<ICodOrderConfirmationProps<ICodOrderConfirmationData>>}
 */
class CodOrderConfirmation extends React.PureComponent<ICodOrderConfirmationProps<ICodOrderConfirmationData>, { isLoading: boolean }> {
    constructor(props: ICodOrderConfirmationProps<ICodOrderConfirmationData>) {
        super(props);
        this.state = {
            isLoading: true
        };
    }

    public componentDidMount() {
        // Simulate data loading
        setTimeout(() => {
            this.setState({ isLoading: false });
        }, 1000); // Simulating a delay for loading, adjust as needed
    }

    private getQueryParams(): { orderId: string | null; isCod: boolean } {
        if (typeof window !== 'undefined') {
            const url = window.location.href;

            // Find the first occurrence of '?' and consider the rest as the query string
            const queryStringStartIndex = url.indexOf('?');
            let queryString = queryStringStartIndex !== -1 ? url.slice(queryStringStartIndex + 1) : '';

            // Replace any additional '?' with '&' to handle incorrectly formatted URLs
            queryString = queryString.replace(/\?/g, '&');

            // Now create URLSearchParams with the cleaned-up query string
            const params = new URLSearchParams(queryString);

            // Extract the 'orderid' and 'iscod' values
            const orderId = params.get('orderid');
            const isCod = params.get('iscod') === 'true';

            return { orderId, isCod };
        }

        // Default return for server-side or if window is undefined
        return { orderId: null, isCod: false };
    }

    public render(): JSX.Element | null {
        const { isLoading } = this.state;
        const { orderId, isCod } = this.getQueryParams();

        return this.props.renderView({ ...this.props, orderId, isCod, isLoading });
    }
}

export default CodOrderConfirmation;
