/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { IOurStoresData } from './our-stores.data';
import { IOurStoresProps } from './our-stores.props.autogenerated';

export interface IOurStoresViewProps extends IOurStoresProps<IOurStoresData> {
    markers: {
        markerContent: string;
        position: [number, number];
    }[];
}

/**
 *
 * OurStores component
 * @extends {React.PureComponent<IOurStoresProps<IOurStoresData>>}
 */
class OurStores extends React.PureComponent<IOurStoresProps<IOurStoresData>> {
    public render(): JSX.Element | null {
        const markers: { markerContent: string; position: [number, number] }[] = [
            {
                markerContent: '<div>Marker 1</div>',
                position: [-118.270293, 34.039737]
            },
            {
                markerContent: '<div>Marker 2</div>',
                position: [-118.283102, 34.021859]
            }
        ];

        const viewProps: IOurStoresViewProps = {
            ...this.props,
            markers
        };

        return this.props.renderView(viewProps);
    }
}

export default OurStores;
