/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/* eslint-disable no-duplicate-imports */
import AccountManagementAddress from './account-management-address';
import AccountManagementAddressView from './account-management-address.view';

export * from './account-management-address';
export * from './account-management-address.data';
export * from './account-management-address.props.autogenerated';
export * from './account-management-address.view';

export { AccountManagementAddress, AccountManagementAddressView };
