/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/* eslint-disable no-duplicate-imports */
import CheckoutPaymentInstrument from './checkout-payment-instrument';
import CheckoutPaymentInstrumentView from './checkout-payment-instrument.view';

export * from './actions/get-card-payment-accept-point';
export * from './checkout-payment-instrument';
export * from './checkout-payment-instrument.data';
export {
    ICheckoutPaymentInstrumentConfig,
    ICheckoutPaymentInstrumentProps,
    ICheckoutPaymentInstrumentResources
} from './checkout-payment-instrument.props.autogenerated';
export * from './checkout-payment-instrument.view';
export * from './components';

export { CheckoutPaymentInstrument, CheckoutPaymentInstrumentView };
