/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/* eslint-disable no-duplicate-imports */
import CheckoutGiftCard from './checkout-gift-card';
import CheckoutGiftCardView from './checkout-gift-card.view';

export * from './checkout-gift-card';
export * from './checkout-gift-card.data';
export * from './checkout-gift-card.props.autogenerated';
export * from './checkout-gift-card.view';
export * from './components';

export { CheckoutGiftCard, CheckoutGiftCardView };
