import React, { useState } from 'react';
import { INodeProps, Node, Modal, Button } from '@msdyn365-commerce-modules/utilities';
// import { ICheckoutCodOptionProps } from '../checkout-cod-option.props.autogenerated';
// import { ICheckoutCodOptionData } from '../checkout-cod-option.data';
import { IImageData, Image } from '@msdyn365-commerce/core';
import { ICheckoutGiftCardViewProps } from '../checkout-cod-option';

interface MobileModalProps {
    isOpen: boolean;
    onClose: () => void;
    resources: {
        mobileNumberHeadingLabel: string;
        mobileNumberHeadingDescription: string;
        mobileNumberInputLabel: string;
        mobileNumberCodeMessage: string;
        mobileNumberGetOTPText: string;
        otpVerificationHeadingLabel: string;
        otpVerificationChangePhoneLabel: string;
        otpVerificationValidationMessage: string;
        otpVerificationConfirmOtpLabel: string;
        otpVerificationResendLabel: string;
    };
    props: ICheckoutGiftCardViewProps;
}

const MobileModal: React.FC<MobileModalProps> = ({ isOpen, onClose, resources, props }) => {
    const [currentStep, setCurrentStep] = useState<'enterMobile' | 'verifyOtp'>('enterMobile');
    const [mobileNumber, setMobileNumber] = useState('');
    const [otp, setOtp] = useState('');
    const [otpErrorMessage, setOtpErrorMessage] = useState('');
    const [mobileNumberErrorMessage, setMobileNumberErrorMessage] = useState('');
    const [loading, setLoading] = useState(false);

    const handleMobileNumberChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setMobileNumber(e.target.value);
    };

    const handleOtpChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const value = e.target.value;
        if (/^\d{0,4}$/.test(value)) {
            setOtp(value);
        }
    };

    const handleMobileNumberSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        const mobileNumberPattern = /^[1-9]\d{9}$/; // Replace this pattern with the desired validation pattern
        if (!mobileNumberPattern.test(mobileNumber)) {
            setMobileNumberErrorMessage('Please enter a valid 10-digit mobile number.');
            return;
        }

        setLoading(true);
        // Implement your logic to send OTP
        const isOtpSent = true; // Replace with actual OTP sending logic
        setLoading(false);

        if (isOtpSent) {
            setCurrentStep('verifyOtp');
            setMobileNumberErrorMessage('');
        } else {
            // Handle error in sending OTP
        }
    };

    const handleOtpSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        // Implement your OTP verification logic
        const isOtpValid = otp === '1234'; // Replace with actual OTP verification logic
        setLoading(false);

        if (isOtpValid) {
            // Handle successful OTP verification
            onClose();
        } else {
            setOtpErrorMessage(resources.otpVerificationValidationMessage);
        }
    };

    const _notifyMeModalContainer = (): INodeProps => {
        return {
            tag: Modal,
            placement: 'center',
            hideArrow: true,
            className: 'ms-mobile-number-verify_modal-container',
            wrapClassName: 'ms-mobile-number-verify__modal',
            isOpen,
            toggle: onClose
        };
    };

    const renderMobileNumberOTPImage = (props: ICheckoutGiftCardViewProps): JSX.Element | null => {
        const mobileNumberOTPImage: IImageData | undefined = props.config.mobileNumberOTPImage;
        if (!mobileNumberOTPImage || !mobileNumberOTPImage.src) {
            return null;
        }
        return (
            <Image
                altText={mobileNumberOTPImage.altText}
                className='msc-autoSuggest__productResults-no-results-image-img'
                gridSettings={props.context.request.gridSettings!}
                src={mobileNumberOTPImage.src}
            />
        );
    };

    const renderOTPVerificationImage = (props: ICheckoutGiftCardViewProps): JSX.Element | null => {
        const otpVerificationImage: IImageData | undefined = props.config.otpVerificationImage;
        if (!otpVerificationImage || !otpVerificationImage.src) {
            return null;
        }
        return (
            <Image
                altText={otpVerificationImage.altText}
                className='msc-autoSuggest__productResults-no-results-image-img'
                gridSettings={props.context.request.gridSettings!}
                src={otpVerificationImage.src}
            />
        );
    };

    return (
        <Node {..._notifyMeModalContainer()}>
            <Node className='ms-mobile-number-verify__header msc-modal__header'>
                <Button className='msc-modal__close-button' aria-label='Close' onClick={onClose}></Button>
            </Node>
            <Node className='ms-mobile-number-verify__body msc-modal__body'>
                {loading && <p>Loading...</p>}
                {!loading && currentStep === 'enterMobile' && (
                    <form onSubmit={handleMobileNumberSubmit}>
                        {renderMobileNumberOTPImage(props)}
                        <h2>{resources.mobileNumberHeadingLabel}</h2>
                        <p>{resources.mobileNumberHeadingDescription}</p>
                        <input
                            type='text'
                            value={mobileNumber}
                            onChange={handleMobileNumberChange}
                            placeholder={resources.mobileNumberInputLabel}
                        />
                        {mobileNumberErrorMessage && <p className='error'>{mobileNumberErrorMessage}</p>}
                        <Button type='submit'>{resources.mobileNumberGetOTPText}</Button>
                    </form>
                )}
                {!loading && currentStep === 'verifyOtp' && (
                    <form onSubmit={handleOtpSubmit}>
                        {renderOTPVerificationImage(props)}
                        <h2>{resources.otpVerificationHeadingLabel}</h2>
                        <Button onClick={() => setCurrentStep('enterMobile')}>{resources.otpVerificationChangePhoneLabel}</Button>
                        <input type='text' value={otp} onChange={handleOtpChange} placeholder='Enter OTP' />
                        {otpErrorMessage && <p className='error'>{otpErrorMessage}</p>}
                        <Button type='submit'>{resources.otpVerificationConfirmOtpLabel}</Button>
                    </form>
                )}
            </Node>
        </Node>
    );
};

export default MobileModal;
