/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/* eslint-disable no-duplicate-imports */
import CheckoutBillingAddress from './checkout-billing-address';
import CheckoutBillingAddressView from './checkout-billing-address.view';

export * from './checkout-billing-address';
export * from './checkout-billing-address.data';
export {
    ICheckoutBillingAddressConfig,
    ICheckoutBillingAddressProps,
    ICheckoutBillingAddressResources
} from './checkout-billing-address.props.autogenerated';
export * from './checkout-billing-address.view';

export { CheckoutBillingAddress, CheckoutBillingAddressView };
